configfile: "config/config.yaml"

rule all:
	input:
		"Data/HMMs/HMMsearch_results/After_UPI/{threshold}/{cluster}.out"


rule UPIMAPI_search:
	input:
		sequence="workflow/Data/FASTA/literature_seq/lit_sequences.fasta",
		database="workflow/Data/FASTA/DataBases/familiesDB.fasta"
	output:
		"workflow/Alignments/BLAST/results/upimapi_results/UPIMAPI_results.tsv"
	params:
		outdir="workflow/Alignments/BLAST/results/upimapi_results"
	threads: 8
	log:
		"logs/UPIMAPI_search.log"
	conda:
		"envs/"
	shell:
		"upimapi.py -i {input.sequence} -o {params.outdir} -db {input.database} -t {threads}"


rule UPIMAPI_parse:
	input:
		"workflow/Alignments/BLAST/results/upimapi_results/UPIMAPI_results.tsv"
	output:
		"workflow/Data/Tables/UPIMAPI_results_per_sim.tsv"
	conda:
		"envs/"
	script:
		"scripts/UPIMAPI_parser.py"


rule seq_download:
# esta fica dependente da proxima regra, ou seja, so corre quando se pede a initial_cdhit_per_threshold
	input:
		"Data/Tables/UPIMAPI_results_per_sim.tsv"
	output:
		"Data/FASTA/UPIMAPI/{threshold}.fasta"  # terá que fazer os ficheiros para todos os thresholds de uma só vez
	script:
		"scripts/seq_download.py"


rule initial_cdhit_per_threshold:
	input:
		expand("workflow/Data/FASTA/UPIMAPI/{threshold}.fasta", threshold=config["thresholds"])  # é o output da regra anterior com wildcards
	output:
		"Data/FASTA/UPIMAPI/cd-hit90_after_diamond_{threshold}.fasta"  # sem .clstr porque ele ja vai fazer os dois ficheiros
	shell:
		"docker run --rm -v ~/FASTA/UPIMAPI/:/data/ biocontainers/cd-hit:v4.6.8-2-deb_cv1 bash -c 'cd-hit -i data/{input} -o {output} -c 0.9 -n 5 -M 16000 -d 0 -T 8'"


rule cdhit_parse:
	input:
		"Data/FASTA/UPIMAPI/cd-hit90_after_diamond_{threshold}.fasta.clstr"
	output:
		"Data/Tables/cdhit_clusters_{threshold}_afterUPIMAPI.tsv"
	script:
		"scripts/CDHIT_parser.py"


rule seq_download_cdhit:
	input:
		"Data/Tables/cdhit_clusters_per_threshold_afterUPIMAPI.tsv"
	output:
		"Data/FASTA/CDHIT/{threshold}/{cluster}.fasta"  # um ficheiro por cada cluster, por threshold, com as sequencias
	script:
		"scripts/CDHIT_seq_download.py" # from_cdhit


rule t_coffee:
	input:
	 	"Data/FASTA/CDHIT/{threshold}/{cluster}.fasta"
	output:
		"Alignments/MultipleSequencesAlign/T_Coffee_UPI/{threshold}/{cluster}.clustal_aln"
	shell:
		"docker run --rm -v ~/PDEFinder/:/data pegi3s/tcoffee:latest t_coffee data/{input} -run_name data/{output} -output clustalw_aln"


rule hmmbuild:
	input:
		"Alignments/MultipleSequencesAlign/T_Coffee_UPI/{thresholds}/{cluster}.clustal_aln"
	output:
		"Data/HMMs/After_tcoffee_UPI/{threshold}/{cluster}.hmm"
	shell:
		"docker run --rm -v ~/PDEFinder/:/data biocontainers/hmmer:v3.2.1dfsg-1-deb_cv1 hmmbuild {output} {input}"


rule hmmsearch:
	input:
		"Data/HMMs/After_tcoffee_UPI/{threshold}/{cluster}.hmm",
		"path to DB"
	output:
		"Data/HMMs/HMMsearch_results/After_UPI/{threshold}/{cluster}.out"
	shell:
		"docker run --rm -v ~/PDEFinder/:/data biocontainers/hmmer:v3.2.1dfsg-1-deb_cv1 hmmsearch {input} > {output}"