hmmsearch_outtype: tsv
input_file: lit_sequences.fasta
output_directory: "/mnt/c/Users/Ze/Desktop/Mestrado/3\xBASemestre/TESE/PDETool/results/PlastEDMA_results"
seqids:
- A0A1H6AD45
- G9BY57
- O22443
- Q02567
- Q9HTK9
threads: 1
workflow: annotation
