name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: plastedma:latest
          outputs: type=docker,dest=/tmp/plastedma.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: plastedma
          path: /tmp/plastedma.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: plastedma
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/upimapi.tar
          docker image ls -a

      - name: Check base entrypoint
        run: docker run plastedma /bash -c "ls"

      - name: Annotation workflow by FASTA input, report text creation and excel table format
        run: docker run plastedma /bash -c "plastedma -i UPIMAPI/ci/ids.csv -rd resources_directory --no-annotation"